# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleBooks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for googleBooks
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'UIColor_Hex_Swift'

  target 'googleBooksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'googleBooksUITests' do
    # Pods for testing
  end

end
